### ISSUE TITLE
information is not organized in the URL

### ISSUE THREAD

**Issue by FahimFBA** [javanile/github-traffic#1]
The URL represents this page:
![image](https://user-images.githubusercontent.com/64195132/162947429-ac5c5064-f015-4842-881d-b4438c939259.png)
I think maybe the markdown table is somehow not working there.

**Comment by francescobianco** [comment]
Thanks @FahimFBA ! This was because default markdown processor is not enough on gh-pages. GFM fixed ;-)

**Comment by FahimFBA** [comment]
You're welcome, @francescobianco. Yes, the issue has been resolved on the gh-pages. I am closing this issue then. :)
